### ISSUE TITLE
Ошибка при проверке подписи

### ISSUE THREAD

**Issue by ddvlru** [bmakarenko/gost-crypto-gui#2]
При проверке подписи после выбора файла с суффиксом .sig выводится окно с сообщением:

Произошла ошибка:
0x00000057

Рутокен ЭЦП, КриптоПро v4.0.9006 KC1 Release Ver:4.0.9708, квалифицированный сертификат.

**Comment by bmakarenko** [comment]
Подпись присоединенная или отсоединенная?

**Comment by ddvlru** [comment]
Отсоединённая.

**Comment by bmakarenko** [comment]
Функционал по созданию/проверке отсоединенных подписей еще не реализован. Утилита cryptcp, вокруг которой построен gost-crypto-gui, использует другие ключи для работы с отсоединенными подписями.

**Comment by ddvlru** [comment]
Какие примерно планы по срокам реализации отсоединённых подписей? Готов помочь в тестировании.

**Comment by bmakarenko** [comment]
Ориентировочно в течение мая

**Comment by ddvlru** [comment]
Есть ли новости по поддержке отсоединённой подписи? Можем ли мы как-то помочь? Например, с тестированием.

**Comment by bmakarenko** [comment]
Проверка отсоединенной подписи реализована коммитом 1769aa15b401ea72bc7fe9bf6272468830d36849
