### ISSUE TITLE
Работа с подписанным или зашифрованным файлом

### ISSUE THREAD

**Issue by sibskull** [bmakarenko/gost-crypto-gui#3]
После подписи или шифрования появляется диалоговое окно с именем файла. При этом нет информации об имени подписанного или зашифрованного файла, нет возможности из диалога открыть его или отправить по почте.
Предлагаю переделать диалог:
```
-----------------------------------------------------------
Файл «имя_файла» успешно подписан.

Подписанный файл: имя_файла.sig

[Показать в папке] [Отправить по почте] [Закрыть]
-----------------------------------------------------------
```

**Comment by bmakarenko** [comment]
Теперь можно

**Comment by sibskull** [comment]
Спасибо, всё работает.
