### ISSUE TITLE
error of returt zero-code and ru linux locale

### ISSUE THREAD

**Issue by mrandybu** [bmakarenko/gost-crypto-gui#5]
If method finished with successful, returned zero-code error. look like at screenshot.
![screenshot_20180528_120159](https://user-images.githubusercontent.com/37226388/40607053-015df10c-6270-11e8-85f9-61882955bdc3.png)

**Comment by mrandybu** [comment]
When run method of signing a file in Linux with the Russian locale, an error occurs
![screenshot_20180528_122556](https://user-images.githubusercontent.com/37226388/40608263-94382c24-6273-11e8-8a5a-c8efb7f2b139.png)

**Comment by bmakarenko** [comment]
Version of CryptoPro CSP please. 
Zero return code is formatted the same way on  both 3.6 and 4.0
`[ReturnCode: 0]`
The error message "Произошла ошибка: 0x00000000" should never occur.

**Comment by mrandybu** [comment]
CryptoPro CSP 5.0
fixed my patch, added return code 0

**Comment by mrandybu** [comment]
@bmakarenko what do you think?

**Comment by bmakarenko** [comment]
Fixed, since certified CryptoPro CSP 4.0 R4 uses 0x prefix at return code
5.0 is not certified yet
